"""empty message

Revision ID: c0eaf0f9f2d4
Revises: 
Create Date: 2025-09-26 12:20:47.900252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0eaf0f9f2d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destiny', sa.String(length=200), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('isDisponible', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('responsable', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('worker', 'customer', name='user_types'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reserve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_package_id', sa.Integer(), nullable=False),
    sa.Column('date_reserved', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['trip_package_id'], ['trip_package.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserve')
    op.drop_table('user')
    op.drop_table('trip_package')
    # ### end Alembic commands ###
